#!/usr/bin/env bash
# Initialize a counter
counter=1

# While loop to print "Best School" 10 times
while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((counter++))
done

