#!/usr/bin/env bash
# Initialize a counter
counter=1

# While loop to loop from 1 to 20
while [ $counter -le 20 ]
do
  case $counter in
    4)
	echo "$counter"
      echo "bad luck from China"
      ;;
    9)
	        echo "$counter"
      echo "bad luck from Japan"
      ;;
    17)
	            echo "$counter"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$counter"
      ;;
  esac
  ((counter++))
done

