#!/usr/bin/env bash
# Initialize the hour and minute variables
hour=0

# Loop through hours 0 to 12
while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  
  # Initialize minutes
  minute=1
  
  # Loop through minutes 1 to 59
  while [ $minute -le 59 ]
  do
    echo "$minute"
    ((minute++))
  done
  
  # Increment the hour
  ((hour++))
done

