#!/usr/bin/env bash
# Script to stop the 4-to_infinity_and_beyond process using kill

# Get PIDs of the process and store them in an array
readarray -t PIDS < <(pgrep -f "4-to_infinity_and_beyond")

if [ ${#PIDS[@]} -eq 0 ]; then
    echo "No 4-to_infinity_and_beyond process found."
else
    kill "${PIDS[@]}"
fi

